### ISSUE TITLE
tumble hitstun calculation

### ISSUE THREAD

**Issue by BeedeBdoo** [rubendal/SSBU-Calculator#3]
hitstun doesn't seem to change to tumble hitstun calculation past 80 knockback. It always uses floor(0.4*knockback)-1.

**Comment by rubendal** [comment]
Hitstun calculation with or without tumble uses the same formula, the game just applies a speed up for launched characters, for in-game hitstun considering the speed up function check **Hitstun with speed up** result

Note: Speed up isn't used on moves with FKB

**Comment by BeedeBdoo** [comment]
I see. Thank you! What keep both for then?

**Comment by rubendal** [comment]
Displaying both for anyone who wants to compare the decrease of hitstun frames caused by the speed up effect or compare it with previous Smash games
