### ISSUE TITLE
Color interpolation has some... issues

### ISSUE THREAD

**Issue by 04meta** [rubendal/SSBU-Calculator#4]
`formulas.js:1051-1057`:
```js
function colorLerp(min, max, x, xMin, xMax) {
  if (x <= xMin)
    return min;
  if (x >= xMax)
    return max;
  return (1 - ((x - xMin) / xMax)) * min + ((x - xMin) / xMax) * max;
}
```

On line 1056, `xMax` is used instead of `(xMax - xMin)`, and this leads to values just below the maximum input being colored ... wrongly. Specifically, 199.9% is colored `#f20000`, but 200.0% is colored `#990000`. This makes actual `red`—`#ff0000`—occur at 193% instead of 157% (which would still be a particularly high percent to use `#ff0000` at anyway—I would suggest figuring out what the game actually uses to calculate percents, but...).

**Comment by rubendal** [comment]
Fixed on commit bc84062e46b9eb39c231ba7dc69937d0b99b94af
