### ISSUE TITLE
Weird KO % calculations

### ISSUE THREAD

**Issue by DradeAW** [rubendal/SSBU-Calculator#6]
Hi!

I recently discovered your SSBU calculator and I love it!

I've been doing calculations with Marth, and I've found some weird things.
Here is what I'm using: `https://rubendal.github.io/SSBU-Calculator/multicalc.html?attacker=Marth&target=Banjo%20%26%20Kazooie&baseDamage=18&angle=361&bkb=80&kbg=80&smashAttack=1&hitFrame=10&faf=52&weight=106&gravity=0.11&fallSpeed=1.76&traction=0.076&positionX=65&positionY=0.111259505`

I'm doing an Fsmash tippered with Marth, and I looked at Wario and Captain Falcon. It says wario (`w=107`) dies at 54.76, but Captain Falcon (`w=104`) dies at 80.58.
I tried it in training mode, and they both seem to die at around 50%.

Why does it show such a high value for Captain Falcon? (I didn't try every characters, just these 2)

**Comment by rubendal** [comment]
Both KO calculator and multi calculator seem to be getting the correct calculations on Marth tipper Fsmash with the data you inputted, Captain Falcon is giving 53.7 on the results with Best DI

Please check if you changed something when doing Captain Falcon calculation and try it again, in case something goes wrong send the url after doing the calculation from the Share textbox for both calculations

![image](https://user-images.githubusercontent.com/10661132/84584467-618f4600-adca-11ea-89a8-dbba2e139f70.png)

**Comment by DradeAW** [comment]
Well I'm unable to reproduce the bug I found, if I try to do it again I find the same results as you ^^'

If I find it again I'll screenshot it!
